import React from 'react';
import { AuthProvider } from './context/AuthContext';
import { Header } from './components/layout/Header';
import { LoginForm } from './components/auth/LoginForm';
import { FileUpload } from './components/FileUpload';
import { Summary } from './components/Summary';
import { useAuthContext } from './context/AuthContext';

const Dashboard: React.FC = () => {
  const [fileName, setFileName] = React.useState<string>('');
  const [summary, setSummary] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(false);

  const handleFileUpload = async (file: File) => {
    setFileName(file.name);
    setLoading(true);
    
    // Simulate API call for PDF processing
    setTimeout(() => {
      setSummary("This is a sample summary of the uploaded PDF. In a real implementation, this would be generated by processing the PDF content through an AI model or API.");
      setLoading(false);
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-white">
      <Header />
      <div className="container mx-auto px-4 py-12">
        <div className="flex flex-col items-center justify-center space-y-8">
          <FileUpload onFileUpload={handleFileUpload} />
          <Summary 
            fileName={fileName}
            summary={summary}
            loading={loading}
          />
        </div>
      </div>
    </div>
  );
};

const AppContent: React.FC = () => {
  const { isAuthenticated } = useAuthContext();

  return (
    <div className="min-h-screen bg-gray-50">
      {isAuthenticated ? (
        <Dashboard />
      ) : (
        <div className="min-h-screen flex items-center justify-center px-4">
          <LoginForm />
        </div>
      )}
    </div>
  );
};

function App() {
  return (
    <AuthProvider>
      <AppContent />
    </AuthProvider>
  );
}

export default App;